### ISSUE TITLE
UNABLE TO INSTALL DUE TO vX.X.X

### ISSUE THREAD

**Issue by acadkins327** [apixu/apixu-python#12]
git clone https://github.com/apixu/apixu-python -b vX.X.X  
Cloning into 'apixu-python'...
fatal: Remote branch vX.X.X not found in upstream origin

Followed all steps in described process.
Using Python 3.53 on Raspberry Pi

Best regards,
A. Adkins

**Comment by andreiavrammsd** [comment]
@acadkins327, vX.X.X is just an example version from the documentation. The latest version is v0.1.1.
```
git clone https://github.com/apixu/apixu-python -b v0.1.1
```

**Comment by acadkins327** [comment]
Thank you for the reply which now seems obvious in hind sight.  I
successfully completed all steps.

Best regards,
Al Adkins

**Comment by acadkins327** [comment]
[image: image.jpeg]
I am getting Key Authorization errors.  My Key does NOT work on the Apixu
Interactive?  I does work on the link provided with the signup page:

http://api.apixu.com/v1/forecast.json?key=fa217841ddc34471ba1171359191603&q=Paris

It does not work with your test script.

Started to open an other issue but it would not accept the graphic.

Bet regards.
Al Adkins

**Comment by acadkins327** [comment]
[image: image.png]

I am getting Key Authorization errors.  My Key does NOT work on the Apixu
Interactive?  I does work on the link provided with the signup page:

http://api.apixu.com/v1/forecast.json?key=fa217841ddc34471ba1171359191603&q=Paris

It does not work with your test script.

Started to open an other issue but it would not accept the graphic.

Bet regards.
Al Adkins

**Comment by andreiavrammsd** [comment]
It's not a good idea to post your API key anywhere on the internet. Please generate a new one from your Apixu account.

I've just tested the examples with your API key and it's working. I don't know how you're trying to run the examples, but make sure you're setting the environment variable "APIXUKEY" with your API key.

Eventually, create a repository with your application integration the Apixu library, so I can see exactly what's the issue.

**Comment by acadkins327** [comment]
Regenerated - Thks,
