### ISSUE TITLE
Examples using multilanguage request

### ISSUE THREAD

**Issue by jpint0** [apixu/apixu-python#16]
Hi! 
I'm trying to make requests in Spanish, according to what you see here:
http://www.apixu.com/doc/conditions.json

However I have not been able to enhance any query, since the idle tells me "KeyError" at the time of execution.
Do you have any examples of how to make requests in other languages?

For your time, thank you very much!

**Comment by andreiavrammsd** [comment]
Hi, @jpint0,

This package does not implement the multi language feature of the API yet. I have plans for this and I will get back here when it's done.

Thank you for using Apixu!

**Comment by andreiavrammsd** [comment]
@jpint0, please check [v0.3.0](https://github.com/apixu/apixu-python/releases/tag/v0.3.0).

**Comment by jpint0** [comment]
thank you so much !

I just updated to this new version, however I get the following error when using lang = "is" in my code:

TypeError: __init () __ got an unexpected argument 'lang'

here is my custom action:
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core_sdk import Action
#from rasa_core_sdk.events import SlotSet
from rasa_core.events import SlotSet


class ActionWeather(Action):
	def name(self):
		return 'action_weather'
		
	def run(self, dispatcher, tracker, domain):
		from apixu.client import ApixuClient 
		api_key = '068e666d244e4084a45160554191601' #your apixu key
		client = ApixuClient(api_key=api_key, lang="es")
		
		#loc = ('Valparaiso', tracker.get_slot('ciudad'))[bool(tracker.get_slot('ciudad'))]
		loc = tracker.get_slot('ciudad')
		current = client.current(q=loc)

		city = current['location']['name']
		condition = current['current']['condition']['text']
		temperature_c = current['current']['temp_c']
		humidity = current['current']['humidity']
		wind_mph = current['current']['wind_mph']

		response = """Actualmente está {} en {} en este momento. La temperatura es de {} grados, la humedad es {}% y la velocidad del viento es {} mph.""".format(condition, city, temperature_c, humidity, wind_mph)
		
	
		dispatcher.utter_message(response)
		return [SlotSet('ciudad',loc)]

**Comment by jpint0** [comment]
Sorry my bad. actually all works fine !

thank you!!

**Comment by andreiavrammsd** [comment]
In the sample code above you exposed your Apixu API key. Please go to your Apixu account and generate a new key.
