### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tukaisg** [apixu/apixu-python#2]
![image](https://cloud.githubusercontent.com/assets/24650244/21309931/37a8037c-c606-11e6-9fdc-6b60e98fcc7f.png)

I am having this installation issue .

I did python setup.py install on cmd

**Comment by Narendra-Kumar** [comment]
which python you are using. It works on python 2.7.5

**Comment by tukaisg** [comment]
Im using 3.4.Is this supported ?

**Comment by andreiavrammsd** [comment]
Please come back if you still encounter issues.

**Comment by SakthivelNatrayan** [comment]
Hi,
I am using Python3.7, while executing the below command getting.


Command:

pip install -r requirements.txt


Error:

Collecting git+https://github.com/apixu/apixu-python.git.exe
  Cloning https://github.com/apixu/apixu-python.git.exe to c:\users\sakthi~1\appdata\local\temp\pip-req-build-zpdiby98
error launching git: The system cannot find the path specified.
Command "git clone -q https://github.com/apixu/apixu-python.git.exe C:\Users\SAKTHI~1\AppData\Local\Temp\pip-req-build-zpdiby98" failed with error code 1 in None

Please let me know, how we can fix it.

**Comment by andreiavrammsd** [comment]
@SakthivelNatrayan, do you have Git installed? If you installed GitHub Desktop, Git could have not been installed globally.

Or try to use the non Git method: https://github.com/apixu/apixu-python/#install-apixu-client
