### ISSUE TITLE
Support for weatherstack rebrand?

### ISSUE THREAD

**Issue by holger-zeit** [apixu/apixu-python#20]
Hi!

Love the python library for Apixu!
Now that the API is being rebranded to weatherstack and the old endpoint is shut down on October 14th, 2019, will this library support the new API?

Thanks!
Best, Holger

Link: https://github.com/apilayer/weatherstack#readme

**Comment by andreiavrammsd** [comment]
Hello,

I don't know weatherstack's plans regarding the libraries. The quickest way to use the new API is to use their example: https://weatherstack.com/documentation#python

Regards,
Andrei
