### ISSUE TITLE
Can i nstall with pip that lib ?

### ISSUE THREAD

**Issue by George35mk** [apixu/apixu-python#5]
from apixu.client import ApixuClient, ApixuException
ModuleNotFoundError: No module named 'apixu'

## I try pip install apixu dont work 
then i try pip install WeatherAPIXU and this dont work

**Comment by mohan3d** [comment]
Unfortunately, it's not hosted on **PyPI**.  

You can install directly from git using pip.

`pip install git+<repository_url>`
`pip install git+https://github.com/apixu/apixu-python.git`

**Comment by rachamaduguravi** [comment]
Thanks!

**Comment by sonyasampalli** [comment]
while executing below in cmd hitting an error as " system cant find the file specified while executing command git clone"-- how to overcome this? it would be helpful and can you explain me also why **apixu** is used?
py -3.7 -m pip install git+https://github.com/apixu/apixu-python.git

**Comment by mohan3d** [comment]
@sonyasampalli 

I don't fully understand your issue.

If you want to clone the repo then install it via pip.

```bash
git clone https://github.com/apixu/apixu-python.git
cd apixu-python
pip install .
```

If you want to install it directly from repo (without cloning).

```bash
pip install git+https://github.com/apixu/apixu-python.git
```

**Comment by andreiavrammsd** [comment]
@sonyasampalli, do you have Git installed?
