### ISSUE TITLE
How can I get historical data with Python?

### ISSUE THREAD

**Issue by nikolokas** [apixu/apixu-python#6]
How can I get historical data with Python? This library works only for current and forecast data.

help(client)
Help on ApixuClient in module apixu.client object:

class ApixuClient(builtins.object)
 |  Methods defined here:
 |  
 |  __init__(self, api_key=None, host_url='http://api.apixu.com')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  getCurrentWeather(self, q=None)
 |  
 |  getForecastWeather(self, q=None, days=None)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

**Comment by edumello** [comment]
There is two pull requests with this feature, you can implement then in your code (i dont know if they will add then to the repo)

**Comment by andreiavrammsd** [comment]
@nikolokas, @edumello, please check the new [v0.1.0 version](https://github.com/apixu/apixu-python/releases/tag/v0.1.0) where the `history` was added.
